fix the bug of one hit per layer. cut
milliQan-sw/milliqanOffline pull request #81
Opened 2024-02-20 21:57 UTC by CollinKa

I noticed the oneHitPerLayerCut() method has an issue. The count() in the awkward array can only count the size of arrays. 

Here is the quick test script:
-----------------------------------
import awkward as ak

array = ak.Array([[1, 0, 3], [0, 2, 0], [0, 2, 0]]) # The inner arrays represent the pulse layer inside each event. It is the array from self.events.type.

print(ak.count(array == 0, axis=1)) #It return [3,3,3]

print(ak.count(array == 0, axis=1) == 1)#It return [False,False,Fales]. This replicates the issue from ak.count(self.events.layer==0, axis=1)==1

(ak.count(self.events.layer==0, axis=1)==1)
-----------------------------------
In short the "oneHitPerLayerCut" is to check if the event only contains one pulse instead of one hit per layer.
self.events['oneHitPerLayerCut'] =((ak.count(self.events.layer==0, axis=1)==1) &
(ak.count(self.events.layer==1, axis=1)==1) &
(ak.count(self.events.layer==2, axis=1)==1) &
(ak.count(self.events.layer==3, axis=1)==1))

To fix this bug I modified the oneHitPerLayerCut(), so it checks if the size of pulses for each event is equal to 4 and if the events pass the four layers cut.

Inside the demonstration file oneHITPL.py, the first cutflow that comes with "OLDoneHitPerLayerCut()" is to show bugs.

2024-02-23 18:30 UTC, carriganm95 requested changes
Hi Collin, you are right this is a bug but it can be fixed with the count_nonzero function instead of the changes you suggested. This will avoid loops

2024-02-23 19:53 UTC, CollinKa commented on Run3Detector/analysis/utilities/milliqanCuts.py
> -        self.events['oneHitPerLayerCut'] =((ak.count(self.events.layer==0, axis=1)==1) &
The issue is fixed in the latest commit.

2024-02-26 14:52 UTC, carriganm95 commented on Run3Detector/analysis/utilities/milliqanCuts.py
> +                                           (ak.count_nonzero(self.events.layer==1, axis=1)==1) &
Just remove this big commented section now

2024-02-26 20:17 UTC, carriganm95 approved these changes

2024-02-26 20:18 UTC, carriganm95 approved these changes

2024-02-26 20:18 UTC, merged